language: php

dist: bionic
sudo: false

git:
    depth: 1

jobs:
    fast_finish: true
    include:
        - php: 5.3
          dist: precise
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
        - php: 5.3
          dist: precise
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8
        - php: 5.4
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
        - php: 5.4
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8
        - php: 5.5
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
        - php: 5.5
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8
        - php: 5.6
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
        - php: 5.6
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8
        - php: 7.0
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
        - php: 7.0
          dist: trusty
          env: ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    - ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.0
    - ZABBIX_MINOR=2.4 ZABBIX_PATCH=2.4.8

cache:
    directories:
        - $HOME/.composer

before_install:
    - |
      # General configuration
      stty cols 120
      mkdir -p /opt/zabbix
      wget -qO- https://repo.zabbix.com/zabbix/$ZABBIX_MINOR/ubuntu/pool/main/z/zabbix/zabbix_$ZABBIX_PATCH.orig.tar.gz | tar xvz -C /opt/zabbix
      ln -s /opt/zabbix/zabbix-$ZABBIX_PATCH/frontends/php/ /opt/zabbix/frontend

install:
    - php ./build/build.php
    - composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-interaction --no-scripts

script:
    - ./vendor/bin/phpunit
    - DIFF=$(git diff -p -- src/); if [[ $DIFF ]]; then echo -e "Some files have differences:\n$DIFF" && exit 1; fi;
